### ISSUE TITLE
complie wrong

### ISSUE THREAD

**Issue by xihaizhang** [oyurdakul/klmuc#1]
when i compiled it, it gives me a message that
"Traceback (most recent call last):
  File "C:\Users\zhang\Documents\GitHub\klmuc\mainf.py", line 38, in <module>
    maxim, ub, sn, gens1, buys, sells, al_x1, al_la, al_mu, be, netload = subp(seninp, \
  File "C:\Users\zhang\Documents\GitHub\klmuc\subproblem.py", line 142, in subp
    with open(a, "a+", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sces/sc1.txt'
"
could you pleased be so kind tell me how to deal with this problem.

**Comment by Archiemeng7** [comment]
I have the same problem, it prompts the need for data support files

**Comment by lmd123123** [comment]
I also encountered the same problem as you, did the author not put this file in?

**Comment by Marksuhhh** [comment]
我也是

**Comment by rich-2012** [comment]
I   am also encountering same issue
